[build]
  command = "vite build"
  publish = "dist"
  edge_functions = "false"

[plugins]
  # Disable the Next.js plugin
  "@netlify/plugin-nextjs" = { enabled = false }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200